app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from canteen import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home_view, name='home'),
    # path('search',views.search_result_view, name='search'),
    # path('search_result/',views.search_result_view, name='search'),
]

urlpatterns += [
    path('', include('canteen.urls')),
]

urlpatterns += staticfiles_urlpatterns()

app/canteen/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView, LogoutView,PasswordChangeView,PasswordChangeDoneView



#basic
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search_view, name='search'),
    path('facility/<int:id>', views.dynamic_facility_view, name='facility-view'),
    path('facility_list_staff_view', views.facility_list_staff_view, name='facility_list_staff_view'),
    path('facility_create_view', views.facility_create_view.as_view(), name='facility_create_view'),
    path('facility_update_view/<int:id>', views.facility_update_view.as_view(), name='facility_update_view'),
    path('facility_delete_view/<int:id>', views.facility_delete_view.as_view(), name='facility_delete_view'),
    path('facility_menus_list_staff/<int:id>', views.facility_menus_list_staff, name='facility_menus_list_staff'),
    path('facility_menus_items_list_staff/<int:id>', views.facility_menus_items_list_staff, name='facility_menus_items_list_staff'),
    path('facility_menus_create', views.Facility_menus_create_view.as_view(), name='facility_menus_create'),
    path('menu_items_create', views.Menu_items_create_view.as_view(), name='menu_items_create'),
    path('filter_menu/<int:id_menu>/<str:diet_type>', views.filter_menu, name='filter_menu'),
    path('delete_from_menu/<int:id_menu>/<int:id_item>', views.delete_from_menu, name='delete_from_menu'),
    path('menu/<int:id>', views.menu_view, name='menu'),

    path('order',views.order_view, name='order'),
    path('detail_order_view/<int:id>/',views.detail_order_view, name='detail_order_view'),
    
    path('cart',views.cart_view, name='cart'),
    path('pay',views.pay_view, name='pay'),
    path('add_to_cart/<int:id_item>/<int:id_facility>', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:id_item>/<int:id_facility>', views.remove_from_cart, name='remove_from_cart'),

]

# for admin processes
urlpatterns += [
    path('admin_view', views.admin_view, name='admin_view'),
    path('driver_view', views.driver_view, name='driver_view'),
    path('food_order/', views.food_order_list_view, name='food_order'),
    path('food_order_update/<int:id>', views.Food_order_update_view.as_view(), name='food_order_update'),
    path('food_order_delete/<int:id>', views.Food_order_delete_view.as_view(), name='food_order_delete'),
    path('deliver_order/<int:id>', views.driver_food_order_info, name='deliver_order'),
    path('deliver_order_finally/<int:id>', views.driver_deliver, name='deliver_order_finally'),
    
    path('person_update/<int:id>', views.person_update_view.as_view(), name='person_update'),
    path('person_list_view', views.person_list_view, name='person_list_view'),
    path('person_delete/<int:id>', views.person_delete_view.as_view(), name='person_delete'),


    path('menu_list_view', views.menu_list_view, name='menu_list_view'),
    path('menu_create_view', views.menu_create_view.as_view(), name='menu_create_view'),
    path('menu_update_view/<int:id>', views.menu_update_view.as_view(), name='menu_update_view'),
    path('menu_delete_view/<int:id>', views.menu_delete_view.as_view(), name='menu_delete_view'),
]

urlpatterns += [
    path('operator_view', views.operator_view, name='operator_view'),
    path('food_create_view', views.food_create_view.as_view(), name='food_create'),
    path('food_list_view', views.food_list_view, name='food_list_view'),
    path('food_update_view/<int:id>', views.food_update_view.as_view(), name='food_update_view'),
    path('food_delete_view/<int:id>', views.food_delete_view.as_view(), name='food_delete_view'),

    path('food_order_assign/<int:id_food_order>', views.food_order_assign_view, name='food_order_assign'),
    path('food_order_assign_button_view/<int:id_food_order>/<int:id_person>', views.food_order_assign_button_view, name='food_order_assign_button_view'),
]

# user authentication
urlpatterns += [
    path('register', views.signup, name='register'),
    path('register_with_pay', views.pay_with_signup, name='register_with_pay'),
    path('login', LoginView.as_view(), name='login_url'),
    path('logged', views.logged_view, name='loggend_on'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile', views.profile_view, name='profile'),
    path('profile_edit', views.profile_edit, name='profile_edit'),
    path('change_password', PasswordChangeView.as_view( template_name='password_change_form.html'), name='change_password'),
    path('password_change_done', PasswordChangeDoneView.as_view( template_name='password_change_done.html'), name='password_change_done'),
]

app/test1/test1/urls.py
from django.contrib import admin
from django.urls import path, include

#from canteen import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home_view, name='home'),
    # path('search',views.search_result_view, name='search'),
    # path('search_result/',views.search_result_view, name='search'),
]

urlpatterns += [
    path('', include('canteen.urls')),
]

app/canteen/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

from django.contrib.auth.models import AbstractUser
from django.utils.html import escape, mark_safe
from django.conf import settings
from django.db import models

from django.contrib.auth.models import User

from django.core.exceptions import PermissionDenied


class Facility(models.Model):
    id_facility = models.AutoField(
        primary_key=True)  # basically IntegerField but with autoincrementation so after all Primary Key
    address = models.CharField(max_length=150, blank=False)
    name = models.CharField(max_length=150, blank=False)
    deadline = models.TimeField(blank=False)
    max_ordered_meals = models.IntegerField(default=1)
    image = models.CharField(max_length=100, blank=False, null=True)

    def get_absolute_url(self):
        return f"facility/{self.id_facility}"

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name


class Menu(models.Model):
    id_menu = models.AutoField(primary_key=True)
    date = models.DateField(blank=True, null=True)
    max_items = models.IntegerField(default=10)

    MENU_TYPES = (
        ('d', 'Daily'),  # Changes every day
        ('s', 'Static'),  # Doesn't change
    )

    type = models.CharField(
        max_length=1,
        choices=MENU_TYPES,
        default='s',  # By default will be static menu
    )

    def get_absolute_url(self):
        return f"{self.id_menu}"


class Item(models.Model):
    id_item = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=320, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    image = models.CharField(max_length=100, blank=False, null=True)

    DIET_TYPES = (
        ('n', 'normal'),
        ('v', 'vegetarian'),
        ('g', 'gluten-free'),
    )

    diet_type = models.CharField(
        max_length=1,
        choices=DIET_TYPES,
        default='n',
    )

    def get_absolute_url(self):
        return f"{self.id_item}"

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name


class Person(models.Model):
    id_person = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=50, blank=False)
    surname = models.CharField(max_length=50, blank=False)
    address = models.CharField(max_length=150, blank=False)
    telephone = models.CharField(max_length=25, blank=False, unique=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    email = models.CharField(max_length=32, unique=True, blank=True, null=True)

    ROLES = (
        ('a', 'administrator'),
        ('o', 'operator'),
        ('d', 'driver'),
        ('v', 'visitor'),
        ('r', 'registered')
    )
    role = models.CharField(
        max_length=1,
        choices=ROLES,
        blank=False,
        default='v'
    )

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.surname

    def get_absolute_url(self):
        return f"{self.id_person}"

    def is_admin(self):
        if self.role == 'a' or self.role == 'o' or self.role == 'd':
            pass
        else:
            raise PermissionDenied()

    def is_operator(self):
        if self.role == 'o' or self.role == 'a':
            pass
        else:
            raise PermissionDenied()

    def is_driver(self):
        if self.role == 'd' or self.role == 'a':
            pass
        else:
            raise PermissionDenied()


class Food_order(models.Model):
    id_food_order = models.AutoField(primary_key=True)
    date_created = models.DateTimeField(default=datetime.now)
    date_paid = models.DateTimeField(blank=True, null=True)
    date_approved = models.DateTimeField(blank=True, null=True)
    date_delivered = models.DateTimeField(blank=True, null=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, blank=True,
                               null=True)  # because if user isn't authenticated that's why we need it blank and null, It will be added later in the checkout
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE, blank=True,
                                 null=True)  # because user can make an order just by seeing the cart and he also may remove all the items from cart and then order new items from another facility
    approved_by = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='Approved_by', blank=True, null=True)
    delivered_by = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='Delivered_by', blank=True,
                                     null=True)

    FOOD_ORDER_STATUS = (
        ('o', 'ordered'),
        ('p', 'paid'),
        ('a', 'approved'),
        ('c', 'canceled'),
        ('d', 'delivered'),
    )

    status = models.CharField(
        max_length=1,
        choices=FOOD_ORDER_STATUS,
        default='o',
    )

    def get_absolute_url(self):
        return f"{self.id_food_order}"

    def get_absolute_url_id(self):
        return reverse('food_order', kwargs={'id': self.id_food_order})


class Food_order_item(models.Model):
    id_food_order = models.ForeignKey(Food_order, on_delete=models.CASCADE)
    id_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        unique_together = (('id_food_order', 'id_item'),)


class Facility_menus(models.Model):
    id_facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    id_menu = models.OneToOneField(Menu, on_delete=models.CASCADE, primary_key=True)


class Menu_items(models.Model):
    id_menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    id_item = models.ForeignKey(Item, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('id_menu', 'id_item'),)

app/canteen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

from django.views.generic.edit import *


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class SearchForm(forms.Form):


    class Meta:
        model =Person

    pass

class Food_order_form(forms.ModelForm):
    class Meta:
        model = Food_order
        fields =[
            'id_food_order',
            #'date_created',
            #'date_paid',
            #'date_approved',
            #'date_delivered',
            #'person',
            #'facility',
            #'delivered_by',
            'status'
        ]

class person_form(forms.ModelForm):
    class Meta:
        model = Person
        fields =[
            'id_person',
            'firstname',
            'surname',
            'address',
            'telephone',
            'user',
            'role',
        ]

class Food_form(forms.ModelForm):
    class Meta:
        model = Item
        fields =[
            'id_item',
            'name',
            'description',
            'price',
            'image',
            'diet_type'
        ]

class Pay_form(forms.ModelForm):
    class Meta:
        model = Person
        fields =[
            
            'firstname',
            'surname',
            'address',
            'telephone',
            
        ]

class Menu_form(forms.ModelForm):
    class Meta:
        model = Menu
        fields =[
            
            'date',
            'max_items',
            'type',
            
        ]


class Facility_form(forms.ModelForm):
    class Meta:
        model = Facility
        fields =[
            
            'address',
            'name',
            'deadline',
            'max_ordered_meals',
            
        ]

class Facility_menus_form(forms.ModelForm):
    class Meta:
        model = Facility_menus
        fields =[
            
            'id_facility',
            'id_menu'
            
        ]

class Menu_items_form(forms.ModelForm):
    class Meta:
        model = Menu_items
        fields =[
            
            'id_menu',
            'id_item'
            
        ]

class UserUpdate(UpdateView):


    """
    model = Author
    fields = ['name']
    template_name_suffix = '_update_form'
    """


    pass

class SignUpForm(UserCreationForm):

    firstname = forms.CharField(max_length=30, required=False)
    surname = forms.CharField(max_length=30, required=False)
    address = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
    telephone = forms.CharField(max_length=30, required=False)

    class Meta:
        model = User
        fields = ['username', 'firstname', 'surname', 'email','address','telephone', 'password2', 'password1']

class EditProfileForm(forms.Form):
    #user = forms.CharField(max_length=30, required=False, help_text='First Name.')

    firstname = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={"class":"tmpclass"}))
    surname = forms.CharField(max_length=30, required=False)
    address = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
    telephone = forms.CharField(max_length=30, required=False)

app/canteen/templates/cart.html
 {% extends "base.html" %}

        {% block content %}

        {% if food_order_instance %}
            <h2 class="page-title">Checkout</h2>
            <div class="checkout-block">

                <div class="side-order-block">
                    <h2><a href=/facility/{{ facility_instance.id_facility }}><i class="fa fa-angle-left" style="font-size: 30px"></i></a> Ordering from: {{ facility_instance.name }}</h2>
                    <hr style="margin: 8px 0 4px">

                    {% for instance_item in food_order_items_list %}
                        <p style="float:left">{{instance_item.id_item.name}} ({{ instance_item.id_item.price }}€)</p>
                        <p style="float:right">{{instance_item.quantity}}x | <a href="{%url 'add_to_cart' instance_item.id_item.id_item food_order_instance.facility.id_facility%}" class="">+1 </a>/<a href="{%url 'remove_from_cart' instance_item.id_item.id_item food_order_instance.facility.id_facility%}" class=""> -1</a></p>
                        <br>
                    {%endfor%}

                        <hr style="margin: 4px 0 20px">
                        <p style="text-align: center; font-size: 40px"><b>Total:  {{price}} €</b></p><br>
                </div>

                <form action="/pay" id="pay_submit">
                    <input type="submit" class="button-black" style="margin-left: auto; margin-right: auto; display:block" value="Pay">
                </form>
                <br>
                {%if unregistered%}
                    <input type="checkbox" id="RBP" value="RBP" onchange="selectionChanged(this)"/><label>&nbsp;I want to register before payment</label>
                    <br>
                {%endif%}
            </div>

            <script>
            function selectionChanged(element){
                if (element.checked){
                    document.getElementById('pay_submit').action = 'register_with_pay';
                }
                else{
                    document.getElementById('pay_submit').action = 'pay';
                }
            }
            </script>


        {% else %}
        <h2 class="notice">Cart is empty</h2>
        {% endif %}

       {% endblock %}

app/canteen/templates/facility_detail.html
 {% extends "base.html" %}

        {% block content %}

        <div class="search-header">
            <h2 class="page-title"><a href="/"><i class="fa fa-angle-left"></i></a> {{ object.name }}'s menus</h2>
        </div> <!-- End search-header -->

        <div class="menu-blocks">
        {%if menu_objs %}
        {% for instance_menu in menu_objs %}
            <a clss="block-link" href="{%url 'menu' instance_menu.id_menu%}">
                <div class="menu-block">
                    <!--Menu #{{instance_menu.id_menu}}<br>-->

                    {% if instance_menu.type == "d" %}
                        Daily menu<br>
                        {{ instance_menu.date}}<br>

                        {% now "Y-m-d" as todays_date %}
                        {% if todays_date == instance_menu.date|date:"Y-m-d" %}
                            Today's menu<br>
                        {% elif todays_date < instance_menu.date|date:"Y-m-d" %}
                            Future menu<br>
                        {% else %}
                        <span style="color:red">Expired menu</span><br>
                        {% endif %}
                    {% else %}
                        <br>
                        Constant menu<br>
                        <br>
                    {% endif %}
                </div><!-- End menu-block -->
            </a>
        {% endfor %}

        {% endif %}
        </div><!-- End menu-blocks -->
        <div class="cart-block">
                <button class="button-black" onclick="window.location='/cart';">
                To checkout
                </button>
        </div><!-- End cart-block -->

        {% endblock %}

app/canteen/templates/facility_staff_view.html
{% extends "base.html" %}

{% block content %}

    <h2 class="page-title"><a href="/operator_view"><i class="fa fa-angle-left"></i></a> Facilities</h2>


    <div class="register-block">
        {% for instance in facility_instance_list%}

            <div style="display: flex;">
                <div style=" width:40%; text-align: left; padding: 10px; display: inline-block">
                    {{ instance.id_facility }}. {{instance.name}}
                </div>
                <div style="width:60%; padding: 10px; text-align: right;"><a class="hoverLink" href="{%url 'facility_update_view' instance.id_facility %}">Update</a> |
                 <a class="hoverLink" href="{%url 'facility_delete_view' instance.id_facility %}">Delete</a> |
                 <a class="hoverLink" href="{%url 'facility_menus_list_staff' instance.id_facility %}">Menus</a>
                </div>
            </div>
            <hr>
        {% endfor %}
        <br>
        <a href="facility_create_view"><button class="button-black">Add new facility</button></a>
    </div>

{% endblock %}

app/canteen/templates/food_create_view.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="page-title">Add new food</h2>

    <div class="register-block">


        <form action='' method='POST'>{% csrf_token %}
            <div class="form-class">
                {{ form.as_p }}
            </div>
            <input type='submit' value='Save' />
        </form>
    </div>

{% endblock %}

app/canteen/templates/food_order_update_view.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="page-title"><a href="/food_order"><i class="fa fa-angle-left"></i></a> Food order update</h2>

    <div class="register-block">

        <form action='' method='POST'>    {% csrf_token %}
            <div class="form-class">
                <div style="width: 400px; margin-left: 15px; font-size: 18px">
                    {% if view.get_instance.status == "o" %}
                        <p>Status: ordered</p>
                    {% endif %}
                    {% if view.get_instance.status == "p" %}
                        <p>Status: paid</p>
                    {% endif %}
                    {% if view.get_instance.status == "a" %}
                        <p>Status: approved</p>
                    {% endif %}
                    {% if view.get_instance.status == "c" %}
                        <p>Status: canceled</p>
                    {% endif %}
                    {% if view.get_instance.status == "d" %}
                        <p>Status: delivered</p>
                    {% endif %}
                    <p>Person: {{view.get_instance.person}}</p>
                    <p>Username: {{view.get_instance.person.user.username}}</p>
                    <p>Facility: {{view.get_instance.facility}}</p>
                    {% if view.get_instance.delivered_by.user.username %}
                    <p>Delivered by: {{view.get_instance.delivered_by.user.username}}</p>
                    {% endif %}
                    <br>
                </div>
                <hr style="margin: 10px 10px">
                {{ form.as_p }}
            </div>
            
            <input type='submit' class="button-black" value='Save' onclick="myFunction()"/>
        </form>
    </div>


    <script>
        function myFunction() {
            alert("It was saved");
        }
        </script>


    
    
{% endblock %}

app/canteen/templates/index.html
 {% extends "base.html" %}

        {% block content %}
        <!-- End main-header -->

        {% load static %}

        <div class="search-header">
            <h2 class="page-title">All facilities</h2>
            <form class="search-bar" action="{% url 'search' %}">
                <button type="submit"><i class="fa fa-search"></i></button>              
                <input type="text" placeholder="Search..." style="margin-bottom: 0px; margin-top: 0px;" name="search_form">
            </form>  
        </div> <!-- End search-header -->
        <div class="content">
            {% for instance in object %}
            <a clss="block-link" href='{{instance.get_absolute_url}}'>
                <div class="facility-block">
                    {% if instance.image != None %}
                    <img src="{% static instance.image %}" width="400px" height="200px">
                    {% endif %}
                    <b>{{ instance.name}}</b><br>
                    {{ instance.address }}<br>
                    Order deadline: {{ instance.deadline|date:"G:i" }}
                </div>
            </a>
            {% endfor %}
        </div> <!-- End content -->

        {% endblock %}

app/canteen/templates/menu_create_view.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="page-title">Create new menu</h2>

    <div class="register-block">
        Date input:YYYY-MM-DD
        <hr>

        <form action='' method='POST'>{% csrf_token %}
            <div class="form-class">
                {{ form.as_p }}
            </div>
        <input type='submit' value='Save' />
        </form>
    </div>

{% endblock %}

app/canteen/templates/menu_detail.html
{% extends "base.html" %}

    {% block content %}


    {% load static %}

        <div class="search-header">
            <h2 class="page-title"><a href="/facility/{{ facility.id_facility }}"><i class="fa fa-angle-left"></i></a> Menu items</h2>
        </div> <!-- End search-header -->

    <div>
        <ul style="white-space:nowrap;margin-left:20px;font-weight:bold">
            <li style="display:inline"><a href="{% url 'filter_menu' menu.id_menu 'n'%}">Normal</a></li> |
            <li style="display:inline"><a href="{% url 'filter_menu' menu.id_menu 'v'%}">Vegetarian</a></li> |
            <li style="display:inline"><a href="{% url 'filter_menu' menu.id_menu 'g'%}">Glueten-free</a></li> |
            <li style="display:inline"><a href="{% url 'menu' menu.id_menu %}">All</a></li>
        </ul>
    </div>

    <div class="food-blocks">
    {%if item_objs%}

        {% if menu.type == 's' %}
            {% firstof "" as is_disabled %}
        {% else %}
            {% now "Y-m-d" as todays_date %}
            {% if todays_date == menu.date|date:"Y-m-d" %}
                {% firstof "" as is_disabled %}
            {% else %}
                {% firstof "disabled" as is_disabled %}
            {% endif %}
        {% endif %}

        {% if is_disabled == "disabled" %}
        <br><p style="font-weight:bold;color:red;margin-left:20px"><b>WARNING: You cannot order from this menu, it is not current!</b></p>
        {% endif %}

    {% for instance_item in item_objs %}
        <div class="food-block">
            {% if instance_item.image != None %}
            <img src="{% static instance_item.image %}" width="100px" height="100px" style="float:left;margin-right:10px">
            {% endif %}
            <div style="float:left; max-width: 150px">
                <b>{{instance_item.name}}</b><br>
                {{instance_item.description}}<br>
                {% if instance_item.diet_type == "n" %}
                Diet: normal<br>
                {% elif instance_item.diet_type == "g" %}
                Diet: gluten-free<br>
                {% else %}
                Diet: Vegetarian<br>
                {% endif %}
                <b>{{instance_item.price}} €</b><br>
                <!--<a href="{%url 'add_to_cart' instance_item.id_item id_facility%}" class="">Add to Cart</a><br>-->
            </div>
            <div style="float:right">
                {% if is_disabled == "disabled" %}
                <span style="font-weight:bold;color:red">Cannot order</span>
                {% else %}
                <a href="{%url 'add_to_cart' instance_item.id_item id_facility%}" class="">
                    <button class="button-white" onclick="" style="float:right ">Add to Cart</button>
                </a>
                {% endif %}
            </div>
        </div>

    {% endfor %}

    {%endif%}
    </div><!-- End food-blocks -->

    <div class="cart-block">
        <button class="button-black" onclick="window.location='/cart';">
        To checkout
        </button>
    </div><!-- End cart-block -->


    {% endblock %}

app/canteen/templates/operator_view.html
{% extends "base.html" %}

{% block content %}
    <h2 class="page-title">Operator page</h2>

    <div class="register-block" style="text-align: left">
        <hr><br>
        <h1><a class="hoverLink" href="food_order">Orders <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr><br>
        <h1><a class="hoverLink" href="facility_list_staff_view">Facilities administration <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr><br>
        <h1><a class="hoverLink" href="food_list_view">Food administration <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr><br>
        <h1><a class="hoverLink" href="menu_list_view">Menu administration <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr><br>
        <h1><a class="hoverLink" href="facility_menus_create">Assign menu to Facility <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr><br>
        <h1><a class="hoverLink" href="menu_items_create">Assign food to menu <i class="fa fa-angle-right" style="font-size: 26px"></i></a></h1>
        <br><hr>
    </div>

{% endblock %}

app/canteen/templates/order_detail_view.html
{% extends "base.html" %}

{% block content %}

    <h2 class="page-title"><a href="/order"><i class="fa fa-angle-left"></i></a> Order ID: {{food_order.id_food_order}}</h2>

    <div class="register-block">
        <h2>From: {{food_order.facility}}</h2>
        <hr><br>
        {% for instance in food_order_items %}
            {{instance.quantity}}x {{instance.id_item.name}} | ({{instance.id_item.price}}€)<br>
        {% endfor %}
    <br><hr><br>
    <h2>Total: {{price}} €<br></h2>
    </div>

{% endblock %}

app/canteen/templates/pay_unregistered.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="page-title">Enter your contact information</h2>

    <div class="register-block" style="width: 800px">


        <form action='' method='POST'>{% csrf_token %}
            <div class="row" style="display: flex;">
                <div class="column2-left"><label for="id_firstname">Firstname:</label></div>
                <div class="column2-right"><input type="text" name="firstname" maxlength="50" required id="id_firstname"></div>
            </div>
            <div class="row" style="display: flex;">
                <div class="column2-left"><label for="id_surname">Surname:</label></div>
                <div class="column2-right"><input type="text" name="surname" maxlength="50" required id="id_surname"></div>
            </div>
            <div class="row" style="display: flex;">
                <div class="column2-left"><label for="id_address">Address:</label></div>
                <div class="column2-right"><input type="text" name="address" maxlength="150" required id="id_address"></div>
            </div>
            <div class="row" style="display: flex;">
                <div class="column2-left"><label for="id_telephone">Telephone:</label></div>
                <div class="column2-right"><input type="text" name="telephone" maxlength="25" required id="id_telephone"></div>
            </div>
            <input type='submit' value='Save' />
        </form>
    </div>


{% endblock %}

app/canteen/templates/person_list_view.html
{% extends 'base.html' %}

{% block content %}

     <h2 class="page-title">Users</h2>

    <div class="register-block">

        {% for instance in person_instance_list %}
        <div style="text-align: left;">
            ID: {{instance.id_person}}<br>
            Login: {{instance.user}} <br>
            Firstname: {{instance.firstname}} <br>
            Surname: {{instance.surname}} <br>
            {% if instance.role == "a" %}
                Role: administrator
                {% elif instance.role == "o" %}
                Role: operator
                {% elif instance.role == "d" %}
                Role: driver
                {% else %}
                Role: registered user
                {% endif %}
            <br style="margin-bottom: 10px">
            <span style="font-size: 18px;"><b><a class="hoverLink" href="{%url 'person_update' instance.id_person %}">Update</a></b> |
            <b><a class="hoverLink" href="{%url 'person_delete' instance.id_person %}">Delete</a></b></span><br>
        </div>
            <hr style="margin: 10px 0px">
        {% endfor %}
    </div>

{% endblock %}